### ISSUE TITLE
Query HDT with the javascript comunica

### ISSUE THREAD

**Issue by firmao** [comunica/comunica-actor-init-sparql-hdt#86]
Hi, I just want to query a huge HDT file with comunica.

Here is my HTML page:
```
<html>
<body>
<h1>Agggggg</h1>
<script src="http://rdf.js.org/comunica-browser/versions/1/packages/actor-init-sparql/comunica-browser.js"></script>
<script language="JavaScript">
  Comunica.newEngine().query('SELECT * where { ?s ?p ?o } LIMIT 10',
    { sources: [   { type: 'hdt', value: 'http://lod-a-lot.lod.labs.vu.nl/data/LOD_a_lot_v1.hdt } ] }
	).then(function (result) {
      result.bindingsStream.on('data', function (data) {
        // Each variable binding is an RDFJS term
        console.log(data.get('?s').value + ' ' + data.get('?p').value + ' ' + data.get('?o').value);
      });
    });
</script>
</body>
</html>
```

The file is too large, and I don't have space in my machine.

if possible, could you tell me:
How to query HDT files only providing the link to the file?
How to query multiple HDT files?
How to query multiple files and SPARQL endpoints together? i.g., 3 HDT files + 2 NT files + 3 SPARQL endpoints.

Thanks a lot,

Cheers,

Andre Valdestilhas

**Comment by rubensworks** [comment]
This package makes use of [HDT-Node](https://www.npmjs.com/package/hdt), which _only_ works in Node.js, _not_ in client-side JS in browsers.

If I understand your use case, you want to setup a web service that can call Comunica-HDT on the server-side. The HDT file downloading would be something you would have to implement yourself in the web service, after which you can pass the downloaded HDT files to Comunica-HDT.
