### ISSUE TITLE
Error installing on windows 10

### ISSUE THREAD

**Issue by gitmpje** [comunica/comunica-actor-init-sparql-hdt#87]
I get the following error message when trying to install on windows 10. Is it just not possible to install on windows or am I missing some requirements? (I did not have any problems when installing Comunica SPARQL)
```
'ls' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'ls -1 deps/libhdt/src/bitsequence/*.cpp' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\<username>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<username>\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\<username>\Documents\Tools\comunica-actor-init-sparql-hdt\node_modules\hdt
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN The package @comunica/runner-cli is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hdt@2.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hdt@2.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Roaming\npm-cache\_logs\2020-03-04T17_38_23_437Z-debug.log
```

**Comment by rubensworks** [comment]
This seems to be a problem with your node-gyp installation (which is required because of the HDT-Node dependency).

I'm not a Windows user myself, so I have no idea how to fix something like this.

@joachimvh have you seen this error before in your Windows environment?

**Comment by joachimvh** [comment]
Wel the error here seems to be that `ls` is not part of the path causing the process to stop there. But even if it was, `libhdt` doesn't compile on Windows so there's no solution that will make this work.

**Comment by rubensworks** [comment]
> libhdt doesn't compile on Windows so there's no solution that will make this work.

Are you sure? I thought other people managed to compile HDT-CPP on Windows.
Maybe it requires some magic with node-gyp?

**Comment by joachimvh** [comment]
I have never heard of someone having hdt on Windows and never got it working myself, but I would be glad to be proven wrong. :D

**Comment by rubensworks** [comment]
These commits seem to show that it worked under Windows at some point in time: https://github.com/rdfhdt/hdt-cpp/search?q=windows&type=Commits

**Comment by gitmpje** [comment]
I tried several things but gave up trying to install it on Windows. Instead, I installed it in a docker container, and this did work out. Now I would like to use the SPARQL Endpoint functionality, but I don't get how to start it. Can someone help me with this?

**Comment by rubensworks** [comment]
Docker is indeed a good fallback.

The endpoint can be started like this: https://github.com/comunica/comunica-actor-init-sparql-hdt#usage-as-a-sparql-endpoint

**Comment by gitmpje** [comment]
Thank you for the help. Unfortunately, I can't start the endpoint in the way mentioned in the instructions, so probably there is still something wrong with my installation. I will have to look into this again then.

**Comment by gitmpje** [comment]
I was just looking in the node_modules/.bin folder, where the executables `comunica-sparql` and `comunica-dynamic-sparql` are located, also `hdt` is in this folder. However, `comunica-sparql-hdt-http` not. Am I missing something, or am I looking at the wrong place?

**Comment by rubensworks** [comment]
Ah, you're right, the http binary was missing.

Added and fixed in release 1.5.4.

**Comment by gitmpje** [comment]
Thank you, this problem is now solved. I just wanted to try it out with an open source hdt data file, but now get a new error, when using the following command `comunica-sparql-hdt-http "{ \"sources\": [{ \"type\": \"file\", \"value\" : \"/home/data/wordnet31.hdt\" }]}"`. It looks like it can not find the file, but the file is actually present in the specified folder. Sorry for bothering you so much.
```Server error in results: Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/sparql-queryoperators.json#mediatorResolveQuadPattern mediated over all rejecting actors:
Error: https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql-hdt/^1.0.0/config/sets/resolve-hdt.json#myQuadPatternResolver requires a single source with a hdtFile to be present in the context.
Error: Actor https://linkedsoftwaredependencies.org/bundles/npm/@comunica/actor-init-sparql/^1.0.0/config/sets/resolve-federated.json#myFederatedQuadPatternResolver can only resolve quad pattern queries against a sources array.

**Comment by rubensworks** [comment]
You must use `hdtFile` instead of `file` in your JSON context.

**Comment by gitmpje** [comment]
Great, I missed that one, but now it works! Thank you for your support!
